name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.12.12
  - pip=26.0.1
  - pip:
    - argparse=1.4.0
    - requests=2.32.5
    - cartopy=0.25.0
    - netcdf4=1.7.4
    - xarray=2026.2.0
    - zonda-rotgrid=0.4.1